# Generated by Django 5.0.1 on 2024-02-16 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(choices=[('Tốt', 'Tốt'), ('Hỏng', 'Hỏng')], default='Tốt', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='school_status',
            field=models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Ngưng hoạt động', 'Ngưng hoạt động')], default='Đang hoạt động', max_length=20),
        ),
    ]
