# Generated by Django 5.0.1 on 2024-02-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_asset', to='asset.district'),
        ),
    ]
