# Generated by Django 4.2.3 on 2024-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_status',
            field=models.CharField(choices=[('Đang liên kết', 'Đang liên kết'), ('Ngưng liên kết', 'Ngưng liên kết')], default='Đang hoạt động', max_length=20),
        ),
    ]
