# Generated by Django 4.2.3 on 2024-02-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_school_school_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labroom',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.school'),
        ),
    ]
