# Generated by Django 5.0.1 on 2024-02-27 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_asset_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.school'),
        ),
    ]
