# Generated by Django 5.0.1 on 2024-03-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_asset_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_status',
            field=models.CharField(choices=[('Đang liên kết', 'Đang liên kết'), ('Đàm phán', 'Đàm phán'), ('Ngưng liên kết', 'Ngưng liên kết')], default='Đang hoạt động', max_length=20),
        ),
    ]
