# Generated by Django 4.2.3 on 2024-03-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_alter_school_school_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_status',
            field=models.CharField(choices=[('Đang liên kết', 'Đang liên kết'), ('Đang đàm phán', 'Đang đàm phán'), ('Ngưng liên kết', 'Ngưng liên kết')], default='Đang hoạt động', max_length=20),
        ),
    ]
