# Generated by Django 4.2.3 on 2024-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_alter_school_school_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_status_color',
            field=models.CharField(default='btn-success', max_length=20),
        ),
    ]
