# Generated by Django 5.0.4 on 2024-05-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_school_school_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='school_location',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
