# Generated by Django 5.0.6 on 2024-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_asset_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
