# Generated by Django 5.0.6 on 2024-12-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_alter_asset_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
