# Generated by Django 5.0.7 on 2024-10-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='asset',
        ),
    ]
