# Generated by Django 5.0.7 on 2024-11-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_remove_warehouse_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
    ]
