# Generated by Django 5.2.4 on 2025-09-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_alter_asset_name'),
        ('asset', '0019_alter_asset_created_at'),
    ]

    operations = [
    ]
