# Generated by Django 5.2.4 on 2025-09-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_merge_20250915_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='department',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
