# Generated by Django 5.2.4 on 2025-12-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_remove_school_department_delete_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị'),
        ),
    ]
