from django.urls import path
from . import views 
from .views import UpdateAssetsDepartmentView, UpdateAssetsLabroomView, UpdateAssetsDistrictView

urlpatterns = [
    path('view_department/', views.view_department, name = 'view_department'),
    path('create_department_2/', views.create_department_2, name='create_department_2'),
    path('department_detail/<int:department_id>/', views.department_detail, name='department_detail'),
    path('create_asset_department/<int:department_id>/', views.create_asset_department, name='create_asset_department'),
    path('departments/<int:department_id>/update_assets/', UpdateAssetsDepartmentView.as_view(), name='update_assets_department'),
    path('department_detail_2/<int:department_id>/', views.department_detail_2, name = 'department_detail_2'),
    path('create_district/<int:department_id>/', views.create_district, name ='create_district'),
    path('HaNoienspire/<int:department_id>/<int:district_id>', views.HaNoienspire, name='HaNoienspire'),
    path('create_asset_HaNoi/<int:department_id>/<int:district_id>/', views.create_asset_HaNoi, name = 'create_asset_HaNoi'),
    path('district_detail/<int:department_id>/<int:district_id>/', views.district_detail, name='district_detail'),
    path('create_school/<int:department_id>/<int:district_id>/', views.create_school, name='create_school'),
    path('school_detail/<int:department_id>/<int:district_id>/<int:school_id>/', views.school_detail, name='school_detail'),
    path('create_labroom/<int:department_id>/<int:district_id>/<int:school_id>/', views.create_labroom, name='create_labroom'),
    path('labroom_detail/<int:department_id>/<int:district_id>/<int:school_id>/<int:labroom_id>/', views.labroom_detail, name='labroom_detail'),
    path('create_asset_lab/<int:department_id>/<int:district_id>/<int:school_id>/<int:labroom_id>/', views.create_asset_lab, name='create_asset_lab'),
    path('update_asset_status/', views.update_asset_status, name='update_asset_status'),
    path('update_school_status/', views.update_school_status, name='update_school_status'),
    path('departments/<int:department_id>/districts/<int:district_id>/schools/<int:school_id>/labrooms/<int:labroom_id>/assets/<int:asset_id>/edit/', views.edit_asset_lab, name='edit_asset_lab'),
    path('edit_asset_HaNoi/<int:department_id>/<int:district_id>/<str:asset_id>/', views.edit_asset_HaNoi, name = 'edit_asset_HaNoi'),
    path('edit_asset_department/<int:department_id>/<str:asset_id>/', views.edit_asset_department, name ='edit_asset_department'),
    path('move_asset_labroom/<int:department_id>/<int:district_id>/<int:school_id>/<int:labroom_id>/<int:asset_id>/', views.move_asset_labroom, name='move_asset_labroom'),
    path('get_districts/', views.get_districts, name='get_districts'),
    path('get_schools/', views.get_schools, name='get_schools'),
    path('get_labrooms/', views.get_labrooms, name='get_labrooms'),
    path('move_asset_Hanoi/<int:department_id>/<int:district_id>/<int:asset_id>/', views.move_asset_Hanoi, name='move_asset_Hanoi'),
    path('move_asset_department/<int:department_id>/<int:asset_id>/', views.move_asset_department, name ='move_asset_department'),
    path('delete_asset_lab/<int:department_id>/<int:district_id>/<int:school_id>/<int:labroom_id>/<int:asset_id>/', views.delete_asset_lab, name='delete_asset_lab'),
    path('delete_asset_Hanoi/<int:department_id>/<int:district_id>/<int:asset_id>/', views.delete_asset_Hanoi, name='delete_asset_Hanoi'),
    path('delete_asset_department/<int:department_id>/<int:asset_id>/', views.delete_asset_department, name='delete_asset_department'),
    path('departments/<int:department_id>/districts/<int:district_id>/schools/<int:school_id>/labrooms/<int:labroom_id>/update_assets_labroom/', UpdateAssetsLabroomView.as_view(), name='update_assets_labroom'),
    path('departments/<int:department_id>/districts/<int:district_id>/update_assets_district/', UpdateAssetsDistrictView.as_view(), name='update_assets_district'),
    path('all_broken_asset', views.all_broken_asset, name = 'all_broken_asset'),
    path('all_active_asset', views.all_active_asset, name = 'all_active_asset'),
    path('all_asset', views.all_asset, name = 'all_asset'),
    path('department_all_asset/<int:department_id>/', views.department_all_asset, name ='department_all_asset'),
    path('department_all_asset/<int:department_id>/', views.department_all_asset, name ='department_all_asset'),
    path('district_all_asset/<int:department_id>/<int:district_id>/', views.district_all_asset, name ='district_all_asset'),
    path('update_department_order/', views.update_department_order, name='update_department_order'),
]

