# Generated by Django 5.0.1 on 2024-01-25 03:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_list_id', models.CharField(max_length=25, unique=True)),
                ('task_list_description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('task_list_is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_list_id', models.CharField(max_length=20, unique=True)),
                ('todo_list_title', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('todo_list_status', models.CharField(choices=[('Đang làm', 'Đang làm'), ('Đã xong', 'Đã xong')], default='Đang làm', max_length=50)),
                ('todo_list_create_time', models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 25, 3, 31, 20, 991145, tzinfo=datetime.timezone.utc))),
                ('todo_list_is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
