# Generated by Django 5.0.1 on 2024-01-25 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todo_list_create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 25, 4, 10, 4, 181320, tzinfo=datetime.timezone.utc)),
        ),
    ]
