# Generated by Django 5.0.1 on 2024-01-25 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todolist_todo_list_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todo_list_create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 25, 4, 28, 0, 15294, tzinfo=datetime.timezone.utc)),
        ),
    ]
