# Generated by Django 5.0.1 on 2024-01-25 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todolist_todo_list_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todo_list_create_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 25, 5, 6, 26, 610158, tzinfo=datetime.timezone.utc)),
        ),
    ]
