# Generated by Django 5.0.1 on 2024-01-25 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todolist_todo_list_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todo_list_create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 5, 15, 24, 762407, tzinfo=datetime.timezone.utc)),
        ),
    ]
