# Generated by Django 5.0.1 on 2024-01-25 09:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_todolist_todo_list_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='todo_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_list_create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 9, 1, 35, 454793, tzinfo=datetime.timezone.utc)),
        ),
    ]
