# Generated by Django 4.2.3 on 2024-01-25 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_tasklist_todo_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todo_list_create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 12, 6, 35, 767101, tzinfo=datetime.timezone.utc)),
        ),
    ]
