# Generated by Django 4.2.3 on 2024-01-25 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_todolist_todo_list_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todo_list_create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 14, 15, 3, 998491, tzinfo=datetime.timezone.utc)),
        ),
    ]
