# Generated by Django 5.0.1 on 2024-01-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_todolist_todo_list_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_list_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
