# Generated by Django 5.0.1 on 2024-01-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_tasklist_task_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='task_list_is_unresolved',
            field=models.BooleanField(default=False),
        ),
    ]
