# Generated by Django 5.0.1 on 2024-01-31 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_tasklist_task_list_is_unresolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='task_list_id',
        ),
    ]
