# Generated by Django 5.0.1 on 2024-01-31 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_remove_tasklist_task_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='todo_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.todolist'),
        ),
    ]
