# Generated by Django 5.2.4 on 2025-12-04 07:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avt.jpg', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
