# Generated by Django 5.0.1 on 2024-01-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='school',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
