# Generated by Django 5.0.1 on 2024-01-04 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_resolution_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Lỗi, hãy nhập lại!', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
