# Generated by Django 5.0.1 on 2024-01-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_ticket_contact_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
