# Generated by Django 5.0.1 on 2024-01-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
