# Generated by Django 5.0.1 on 2024-01-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_ticket_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pending',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
