# Generated by Django 5.0.1 on 2024-01-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_remove_ticket_pending_alter_ticket_resolution_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
