# Generated by Django 5.0.1 on 2024-01-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_remove_ticket_comments_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='avatar_url',
            field=models.URLField(default='avatars/avt.jpg'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
