# Generated by Django 5.0.1 on 2024-01-10 02:02

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_comments_avatar_url_alter_comments_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='avatar_url',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to=ticket.models.user_directory_path),
        ),
    ]
