# Generated by Django 5.0.1 on 2024-01-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_comments_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='avatar_url',
        ),
    ]
