# Generated by Django 5.0.1 on 2024-01-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_remove_comments_parent_alter_comments_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticket.ticket'),
        ),
        migrations.DeleteModel(
            name='CommentAuthor',
        ),
    ]
