# Generated by Django 5.0.1 on 2024-01-10 12:28

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_remove_comments_parent_alter_comments_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentauthor',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avt.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avt.jpg', null=True, upload_to=ticket.models.user_directory_path),
        ),
    ]
