# Generated by Django 5.0.1 on 2024-01-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_alter_commentauthor_avatar_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket.comments'),
        ),
    ]
