# Generated by Django 5.0.1 on 2024-01-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_alter_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
