# Generated by Django 5.0.1 on 2024-01-11 08:25

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0032_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentauthor',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avt.jpg', null=True, upload_to=ticket.models.user_directory_path),
        ),
    ]
