# Generated by Django 5.0.1 on 2024-01-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_alter_commentauthor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentauthor',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avt.jpg', null=True, upload_to='avatars/'),
        ),
    ]
