# Generated by Django 5.0.1 on 2024-01-11 11:09

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0034_alter_commentauthor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=ticket.models.user_directory_path),
        ),
    ]
