# Generated by Django 5.0.1 on 2024-01-11 11:31

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0037_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=ticket.models.user_directory_paths),
        ),
    ]
