# Generated by Django 5.0.1 on 2024-01-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0039_ticket_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image2',
        ),
    ]
