# Generated by Django 5.0.1 on 2024-01-11 12:33

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0040_remove_ticket_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=ticket.models.user_directory_paths)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.AddField(
            model_name='ticket',
            name='images',
            field=models.ManyToManyField(blank=True, to='ticket.image'),
        ),
    ]
