# Generated by Django 5.0.1 on 2024-01-11 12:59

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0041_image_remove_ticket_image_ticket_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='images',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=ticket.models.user_directory_paths),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
