# Generated by Django 5.0.1 on 2024-01-11 13:33

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0042_remove_ticket_images_ticket_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='up_video',
            field=models.FileField(blank=True, null=True, upload_to=ticket.models.user_directory_paths),
        ),
    ]
