# Generated by Django 5.0.1 on 2024-01-12 01:56

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0043_ticket_up_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='up_video',
            field=models.FileField(blank=True, default=None, null=True, upload_to=ticket.models.user_directory_paths),
        ),
    ]
