# Generated by Django 5.0.1 on 2024-01-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0044_alter_ticket_up_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
    ]
