# Generated by Django 4.2.3 on 2024-01-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0045_comments_is_editable_reply_is_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_editable',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='is_editable',
        ),
    ]
