# Generated by Django 5.0.1 on 2024-01-22 06:52

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0051_comments_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ticket.models.user_directory_paths),
        ),
    ]
