# Generated by Django 5.0.7 on 2024-12-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0060_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='severity',
        ),
    ]
