# Generated by Django 5.2.4 on 2025-09-19 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0061_remove_ticket_last_modified_remove_ticket_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Lỗi, chỉ nhận ký tự là số!', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
